#Project Information
site_name: Ace Design Library
site_description: 'The Component library for ACE React Apps'
site_author: 'Club Labs'
site_url: 'https://squidfunk.github.io/mkdocs-material/'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 AAA Club Labs'

# Theme Configs
theme:
  name: 'material'
  palette:
    primary: 'blue'  
    accent: 'blue'
  logo: 'images/logo_white.svg'
  language: 'en'

# Page Configs
pages: 
  - Home: index.md
  - Getting Started: gettingStarted.md
  - Brand Standards:
    - Typography: branding/typography.md
    - Pallette: branding/palette.md

  # - Components: components.md
  - Component API: 
    - Button: components/button.md
    - Helper: components/helper.md
    - Input: components/input.md


#Theme Extensions
markdown_extensions:
  - admonition
  - codehilite

extra:
  social:
    - type: 'github'
      link: 'https://github.com/clublabs/ACEDesignSystem'

extra_css: [styles/styles.css]